### Get Users
GET http://localhost:3000/users

### Insert User
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Uazea",
    "password": "hash",
    "email": "aa@a",
    "phone": 25854213
}

### Login with credentials below
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "password": "hash",
    "email": "aa@a"
}

### Remove User
DELETE http://localhost:3000/users
Content-Type: application/json

{
    "username": "Uazea"
}

### Get Recipes
GET http://localhost:3000/recipes

### Insert Recipe
POST http://localhost:3000/recipes
Content-Type: application/json

{
    "title": "Rece title",
    "description": "Recipe description",
    "author": "Gigel Giurgiulescu"
}

### Remove Recipe

DELETE http://localhost:3000/recipes
Content-Type: application/json

{
    "title": "fill"
}