### Get Users
GET http://localhost:3000/users

### Insert User
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "email": "a@a",
    "phone": 1
}

### Login with credentials below
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "password": "test",
    "email": "a@a"
}

### Remove User
DELETE http://localhost:3000/users
Content-Type: application/json

{
    "username": "test"
}

### Get Recipes
GET http://localhost:3000/recipes

### Insert Recipe
POST http://localhost:3000/recipes
Content-Type: application/json

{
    "title": "fill",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed dictum tellus. Vivamus elementum, lorem sed ultrices accumsan, felis arcu hendrerit quam, a vestibulum sem est sed leo. Suspendisse in tempor eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec dictum ex a eros viverra, in eleifend magna consectetur. Vivamus non suscipit enim. Maecenas tempor, eros volutpat congue commodo, nisl magna porttitor lectus, sed lobortis lacus nisl volutpat quam. Nunc interdum lorem nec nibh tristique finibus. Cras vehicula eget mauris ac luctus.",
    "author": "Gigel Giurgiulescu",
    "rating": 5,
    "times_rated": 1
}

### Set a recipe's rating
PATCH http://localhost:3000/recipes
Content-Type: application/json

{
    "title": "Bors",
    "rated": 5
}

### Remove Recipe

DELETE http://localhost:3000/recipes
Content-Type: application/json

{
    "title": "Reteta lu Vlad"
}